export const menu_categories = [
  {
    element: "Academy",
    name: "Academy",
    icon: '<i class="fa-solid fa-graduation-cap"></i>',
    order: "0",
  },
  {
    element: "Help Center",
    name: "Help Center",
    icon: '<i class="fa-regular fa-lightbulb"></i>',
    order: "1",
  },
  {
    element: "Skool Community",
    name: "Community",
    icon: '<i class="fa-solid fa-school-flag"></i>',
    order: "2",
  },
  {
    element: "Referral Form",
    name: "Add Referral",
    icon: '<i class="fa-solid fa-user-plus"></i>',
    order: "3",
  },
  {
    element: "Custom",
    name: "Your Resources",
    order: "4",
    icon: '<i class="fa-solid fa-pencil"></i>',
    submenus: [
      {
        element: "Collab Doc",
        name: "Collab Doc",
        icon: '<i class="fa-solid fa-handshake-simple"></i>',
      },
      {
        element: "Treatment Plan",
        name: "Treatment Plan",
        icon: '<i class="fa-solid fa-syringe"></i>',
      },
      {
        element: "Transformation Plan",
        name: "Transformation Plan",
        icon: '<i class="fa-solid fa-map-location-dot"></i>',
      },
      {
        element: "Mobile App",
        name: "Mobile App",
        icon: '<i class="fa-solid fa-mobile-screen-button"></i>',
      },
    ],
  },
  { element: "Divider", name: "Divider 1", order: "4" },
  {
    element: "Conversations",
    name: "Conversations",
    icon: '<i class="fa-regular fa-comment"></i>',
    order: "5",
  },
  {
    element: "Opportunities",
    name: "Track Leads",
    icon: '<i class="fa-solid fa-user-group"></i>',
    order: "6",
  },
  { element: "Divider", name: "Divider 1", order: "4" },
  {
    element: "Facebook Ads",
    name: "Meta Ads",
    icon: '<i class="fa-brands fa-facebook"></i>',
    order: "8",
  },
  {
    element: "Launch SMS Campaign",
    name: "Launch SMS Campaign",
    icon: '<i class="fa-solid fa-comments"></i>',
    order: "8",
  },
  {
    element: "Marketing",
    name: "Email + Socials",
    icon: '<i class="fa-solid fa-envelopes-bulk"></i>',
    order: "8",
  },
  {
    element: "Booster Shot",
    name: "Booster Shot",
    icon: '<i class="fa-solid fa-gauge-high"></i>',
    order: "8",
  },
  {
    element: "Custom",
    name: "Reporting",
    order: "7",
    icon: '<i class="fa-solid fa-chart-area"></i>',
    submenus: [
      {
        element: "Dashboard",
        name: "Track Results",
        icon: '<i class="fa-solid fa-filter-circle-dollar"></i>',
      },
      {
        element: "Reporting",
        name: "Track Ads",
        icon: '<i class="fa-solid fa-chart-pie"></i>',
      },
    ],
  },
  { element: "Divider", name: "Divider 2", order: "8" },
  {
    element: "Contacts",
    name: "Contacts",
    order: "9",
    icon: '<i class="fa-solid fa-pager"></i>',
  },
  {
    element: "Reputation",
    name: "Manage Reviews",
    order: "10",
    icon: '<i class="fa-solid fa-star"></i>',
  },
  {
    element: "Payments",
    name: "Payments",
    order: "11",
    icon: '<i class="fa-solid fa-wallet"></i>',
  },
  { element: "Divider", name: "Divider 3", order: "13" },
  {
    element: "AI Offer Prompts ",
    name: "AI Prompts",
    order: "12",
    icon: '<i class="fa-solid fa-robot"></i>',
  },
  {
    element: "AI Knowledge",
    name: "AI Knowledge",
    order: "13",
    icon: '<i class="fa-solid fa-brain"></i>',
  },
  {
    element: "Automation",
    name: "Automation",
    order: "14",
    icon: '<i class="fa-solid fa-gear"></i>',
  },
  { element: "Divider", name: "Divider 4", order: "15" },
  {
    element: "Calendars",
    name: "Calendars",
    order: "15",
    icon: '<i class="fa-solid fa-calendar"></i>',
  },
  {
    element: "Sites",
    name: "Sites",
    order: "16",
    icon: '<i class="fa-solid fa-sitemap"></i>',
  },
  { element: "Divider", name: "Divider 4", order: "17" },
  {
    element: "Refer & Get A Free Month",
    name: "Refer & Get A Free Month",
    order: "18",
    icon: '<i class="fa-solid fa-sack-dollar"></i>',
  },
];

export const exclude_accounts = window.exclude_accounts || [
  "lXp9miyd46A0n6RbOxJV",
  "Cm2NZ7Q0aURIfS9C3KTY",
  "daSxurF5JBfQSWKoasXo",
  "SXL7EtDwdfj5cqZSKmIf",
  "lCPfvAYHDBvmnIjFE134",
  "3ph7NZx2kybPjT6R8uJc",
];
