export const calculator_data = {
	full_name: '',
	email: '',
	phone: '',
	street_address: '',
	city: '',
	state: '',
	country: '',
	whats_the_type_of_the_area: '',
	whats_the_angle_of_your_roof: '',
	whats_the_material_of_your_roof: '',
	how_shaded_is_your_area: '',
	whats_your_payment_plan: '',
	your_avg_kw_consumtion: '',
	your_avg_monthly_bill: '',
};
